# Generated by Django 4.2.2 on 2023-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'rejected'), ('3', 'accepted')], default=1, max_length=25),
        ),
    ]
