# Generated by Django 4.2.2 on 2023-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leaverequest_end_date_leaverequest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
